server:
  port: 8888

spring:
  application:
    name: baiduapi
  datasource:
    url: jdbc:mysql://localhost:3306/baiduapi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  web:
    resources:
      static-locations: classpath:/public/uploads
upload:
  directory: uploads
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.tinxing.baiduapi.dao
logging:
  level:
    org.springframework.jdbc: debug
    com.baomidou.mybatisplus.test.autoconfigure: debug

baiduapi:
  client-id: jCA8TzPI9SpRCxfivGFzh3OA
  client-secret: xoO4CoPlmoV7alpGCbVzY8fMGYu2VwLI
